# Generated by Django 4.2 on 2023-07-15 11:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=255, verbose_name='Назнавание')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Imns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Введите номер инспекции', verbose_name='Номер инспекции')),
                ('name', models.CharField(help_text='Введите полное наименование инспекции', max_length=255, verbose_name='Полное наименование инспекции')),
                ('shot_name', models.CharField(help_text='Введите короткое название инспекции', max_length=255, verbose_name='Короткое название инспекции')),
                ('address', models.CharField(help_text='Введите адресс инспекции', max_length=255, verbose_name='Адресс инспекции')),
                ('email', models.CharField(help_text='Введите email', max_length=255, verbose_name='Email')),
                ('post', models.CharField(help_text='Введите почтовый индекс', max_length=255, verbose_name='Почтовый индекс')),
                ('unp', models.CharField(help_text='Введите УНП', max_length=255, verbose_name='УНП')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Введите код риска', max_length=50, verbose_name='Код риска')),
                ('name', models.CharField(help_text='Введите название риска', max_length=255, verbose_name='Название риска')),
                ('description', models.TextField(blank=True, help_text='Введите описание', null=True, verbose_name='Описание')),
                ('enable', models.BooleanField(default=True, help_text='Активен', verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='CIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Введите номер утвержденного отчета', max_length=255, verbose_name='№ утвержденного отчета')),
                ('date_state', models.DateField(help_text='Введите дату утвержденного отчета', verbose_name='Дата утвержденного отчета')),
                ('date_from', models.DateField(help_text='C', verbose_name='Изучаемый периуд с')),
                ('date_to', models.DateField(help_text='По', verbose_name='Изучаемый периуд по')),
                ('count_all', models.IntegerField(help_text='Введите количество документов подвергнутых контролю', verbose_name='Количество документов(фактов), подвергнутых контролю')),
                ('count_contravention', models.IntegerField(help_text='Введите количетво докуметов, в отношении которых установлены нарушения', verbose_name='Количество документов(фактов), в отношении которых установлены нарушения')),
                ('point', models.TextField(help_text='Введите суть нарушения', verbose_name='Краткое содержание(суть), нарушения')),
                ('departments', models.ManyToManyField(to='tvk.department', verbose_name='Подразделение проводившее ТВК')),
                ('imnss', models.ForeignKey(help_text='Код ИМНС субъекта(кто проверяет)', on_delete=django.db.models.deletion.CASCADE, to='tvk.imns', verbose_name='Код ИМНС субъекта(кто проверяет)')),
                ('objects', models.ManyToManyField(help_text='Код ИМНС объекта(кого проверяют)', related_name='objects', to='tvk.imns', verbose_name='Код ИМНС объекта(кого проверяют)')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvk.risk', verbose_name='Код риска')),
            ],
        ),
    ]
