# Generated by Django 4.2 on 2023-07-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('date_state', models.DateField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Imns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('shot_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.CharField(blank=True, max_length=255, null=True)),
                ('unp', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_all', models.IntegerField()),
                ('count_contravention', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('cic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tvk.cic')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tvk.imns')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tvk.risk')),
            ],
        ),
        migrations.AddField(
            model_name='cic',
            name='departments',
            field=models.ManyToManyField(to='tvk.department'),
        ),
        migrations.AddField(
            model_name='cic',
            name='imnss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tvk.imns'),
        ),
    ]
