# Generated by Django 4.2.3 on 2023-08-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='name',
            field=models.TextField(),
        ),
    ]
