# Generated by Django 4.2 on 2023-07-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='department',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='cic',
            name='objects',
        ),
        migrations.AddField(
            model_name='cic',
            name='obj',
            field=models.ManyToManyField(help_text='Код ИМНС объекта(кого проверяют)', related_name='obj', to='tvk.imns', verbose_name='Код ИМНС объекта(кого проверяют)'),
        ),
        migrations.AlterField(
            model_name='cic',
            name='count_contravention',
            field=models.IntegerField(blank=True, help_text='Введите количетво докуметов, в отношении которых установлены нарушения', null=True, verbose_name='Количество документов(фактов), в отношении которых установлены нарушения'),
        ),
        migrations.AlterField(
            model_name='cic',
            name='number',
            field=models.CharField(blank=True, help_text='Введите номер утвержденного отчета', max_length=255, null=True, verbose_name='№ утвержденного отчета'),
        ),
        migrations.AlterField(
            model_name='cic',
            name='point',
            field=models.TextField(blank=True, help_text='Введите суть нарушения', null=True, verbose_name='Краткое содержание(суть), нарушения'),
        ),
        migrations.AlterField(
            model_name='imns',
            name='address',
            field=models.CharField(blank=True, help_text='Введите адресс инспекции', max_length=255, null=True, verbose_name='Адресс инспекции'),
        ),
        migrations.AlterField(
            model_name='imns',
            name='email',
            field=models.CharField(blank=True, help_text='Введите email', max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='imns',
            name='post',
            field=models.CharField(blank=True, help_text='Введите почтовый индекс', max_length=255, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='imns',
            name='unp',
            field=models.CharField(blank=True, help_text='Введите УНП', max_length=255, null=True, verbose_name='УНП'),
        ),
    ]
